apps/amigos/urls.py
from django.conf.urls import url, include
from apps.amigos.views import BuscarAmigos, AgregarAmigos, ListaAmigos
from django.contrib.auth.decorators import login_required

urlpatterns = [
    #url(r'^buscar_amigos$', BuscarAmigos , name='buscar_amigos'),
    url(r'^buscar_amigos/(?P<userentry>\w+)/$', login_required(BuscarAmigos), name='buscar_amigos_search'),
    url(r'^buscar_amigos/$', login_required(BuscarAmigos), name='buscar_amigos'),
    url(r'^agregar_amigo/(?P<id_usuario>\d+)/$', login_required(AgregarAmigos), name='agregar_amigos'),
    url(r'^mis_amigos/$', login_required(ListaAmigos.as_view()), name='lista_amigos'),
]

apps/notas/urls.py
from django.conf.urls import url, include
from apps.notas.views import CrearNotaInd, VerNotasInd, NotaIndDelete, NotaIndEdit, CrearNotaGrup, VerNotasGrup, NotaGrupDelete, NotaGrupEdit
from django.contrib.auth.decorators import login_required

urlpatterns = [
	#Notas Individuales
    url(r'^crear_nota_ind', login_required(CrearNotaInd.as_view()), name='crear_nota_ind'),
    url(r'^notas_ind', login_required(VerNotasInd.as_view()), name='notas_ind'),
    url(r'^borrar_nota_ind/(?P<pk>\d+)/$', login_required(NotaIndDelete.as_view()), name='borrar_nota_ind'),
    url(r'^editar_nota_ind/(?P<pk>\d+)/$', login_required(NotaIndEdit.as_view()), name='editar_nota_ind'),
    #Notas Grupales
    url(r'^crear_nota_grup/(?P<id_grupo>\d+)/$', login_required(CrearNotaGrup), name='crear_nota_grup'),
    url(r'^notas_grup', login_required(VerNotasGrup.as_view()), name='notas_grup'),
    url(r'^borrar_nota_grup/(?P<pk>\d+)/$', login_required(NotaGrupDelete.as_view()), name='borrar_nota_grup'),
    url(r'^editar_nota_grup/(?P<pk>\d+)/$', login_required(NotaGrupEdit.as_view()), name='editar_nota_grup'),


]

rememberNOW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuario/', include('apps.usuarios.urls', namespace='usuarios')),
    url(r'^$', login, {'template_name':'index.html'}, name='login'),
    url(r'^accounts/login/$', login, {'template_name':'index.html'}, name='login2'),
    url(r'^notas/', include('apps.notas.urls', namespace='notas')),
    url(r'^amigos/', include('apps.amigos.urls', namespace='amigos')),
    url(r'^grupos/', include('apps.grupos.urls', namespace='grupos')),
    url(r'^logout/', logout_then_login, name='logout'),


]

apps/amigos/models.py
from django.db import models

# Create your models here.

apps/amigos/forms.py
# -*- encoding:utf-8 -*-
from django import forms

class BusquedaUser(forms.Form):
	busqueda_usuario=forms.CharField(label="Buscar por usuario", max_length=20)

apps/amigos/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.contrib.auth.models import User
from apps.usuarios.models import Usuario
from apps.amigos.forms import BusquedaUser 
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
# Create your views here.

def BuscarAmigos(request, userentry='default'):

	if request.method=='GET':
		usuarios=User.objects.filter(username__contains=userentry)

	if request.method=='POST':
		form = BusquedaUser(request.POST)
		if form.is_valid():
			data= form.cleaned_data
			usuario=data['busqueda_usuario']
			return HttpResponseRedirect(reverse('amigos:buscar_amigos_search', args=(usuario,)))
	else:
		form=BusquedaUser()

	return render(request, "amigos/buscar_amigos.html", {'form':form, 'users':usuarios})

def AgregarAmigos(request, id_usuario):
	amigo=User.objects.get(pk=id_usuario)
	if request.method=='POST':
		actual_user=request.user
		id_actual_usuario=actual_user.pk
		actual_usuario=Usuario.objects.get(propiedades_usuario=id_actual_usuario)
		actual_usuario.amigos.add(amigo)

		actual_amigo=Usuario.objects.get(propiedades_usuario=(amigo.pk))
		actual_amigo.amigos.add(actual_user)

		return redirect('notas:notas_ind')
	return render(request, 'amigos/agregar_amigo.html', {'amigo':amigo})

class ListaAmigos (ListView):
	model=Usuario
	template_name='amigos/amigos.html'
	def get_context_data(self, **kwargs):
	    context = super(ListaAmigos, self).get_context_data(**kwargs)
	    id_actual_usuario=self.request.user.pk
	    actual_usuario=Usuario.objects.get(propiedades_usuario=id_actual_usuario)
	    context['amigos']=actual_usuario.amigos
	    return context

templates/amigos/agregar_amigo.html
{% extends 'base/base.html' %}

{% block contenido %}

<form method="post">
{% csrf_token %}
<h3>Would you like to add: {{amigo.first_name}} {{amigo.last_name}}</h3>
<h4>Username: {{amigo.username}}</h4>
<button class="btn btn-warning" type="submit">Yes</button>
<a href="{% url 'notas:notas_ind' %}">No, thanks</a>

</form>


{% endblock %}

templates/amigos/amigos.html
{% extends 'base/base.html' %}
{% block contenido %}

<h4 id="titulo-amigos">My friends</h4>

<div id="boton-buscar-amigos">
<a id="boton-amigos" class="btn btn-warning" href="{% url 'amigos:buscar_amigos' %}">Find/Add Friends</a>
</div>


<table id="tabla_amigos" class="table table-bordered">
	<thead>
		<tr>
			<td class="table-top">Username</td>
			<td class="table-top">Name</td>
		</tr>
		
	</thead>
	<tbody>
		{% if amigos %}
		{% for user in amigos.all %}
		<tr>
			<td>{{user.username}}</td>
			<td>{{user.first_name}} {{user.last_name}}</td>
		</tr>
		{% endfor %}
		{% else %}
		<h1>You still have no firends.</h1>
		{% endif %}



{% endblock %}

templates/amigos/buscar_amigos.html
{% extends 'base/base.html' %}

{% block contenido %}

<form id="form-buscar-usuario" method='post'>
{% csrf_token %}
	 <div class="row">
    	<div class="col-md-6 col-md-offset-3">
    		<div class="form-group">
        		<label for="busqueda_usuario">Search by Username:  </label>
        		<input class="form-control" type="text" name="busqueda_usuario">
    	   </div>
        </div>
    </div>  
	<button id="boton-buscar" class="btn btn-warning" type="submit">Search!</button>
</form>



<table id="tabla-usuarios" class="table table-bordered">
	<thead>
		<tr>
			<td>username</td>
			<td>nombre</td>
			<td>Solicitud de amistad</td>
		</tr>
		
	</thead>
	<tbody>
		{% if users %}
		{% for user in users %}
		<tr>
			<td>{{user.username}}</td>
			<td>{{user.first_name}} {{user.last_name}}</td>
			<td><a class="btn btn-primary" href="{% url 'amigos:agregar_amigos' user.pk %}">Añadir Amigo </a></td>
		</tr>
		{% endfor %}
		{% else %}
		<h1 id="not-users">There aren´t users with that username!</h1>
		{% endif %}

{% endblock %}

agregar_amigos