apps/amigos/urls.py
from django.conf.urls import url, include
from apps.amigos.views import BuscarAmigos, AgregarAmigos, ListaAmigos
from django.contrib.auth.decorators import login_required

urlpatterns = [
    #url(r'^buscar_amigos$', BuscarAmigos , name='buscar_amigos'),
    url(r'^buscar_amigos/(?P<userentry>\w+)/$', login_required(BuscarAmigos), name='buscar_amigos_search'),
    url(r'^buscar_amigos/$', login_required(BuscarAmigos), name='buscar_amigos'),
    url(r'^agregar_amigo/(?P<id_usuario>\d+)/$', login_required(AgregarAmigos), name='agregar_amigos'),
    url(r'^mis_amigos/$', login_required(ListaAmigos.as_view()), name='lista_amigos'),
]

apps/grupos/urls.py
from django.conf.urls import url, include
from apps.grupos.views import CrearGrupo, VerGrupos
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^crear_grupos$', login_required(CrearGrupo.as_view()) , name='crear_grupos'),
    url(r'^ver_grupos$', login_required(VerGrupos.as_view()) , name='ver_grupos'),
]

apps/notas/urls.py
from django.conf.urls import url, include
from apps.notas.views import CrearNotaInd, VerNotasInd, NotaIndDelete, NotaIndEdit, CrearNotaGrup, VerNotasGrup, NotaGrupDelete, NotaGrupEdit
from django.contrib.auth.decorators import login_required

urlpatterns = [
	#Notas Individuales
    url(r'^crear_nota_ind', login_required(CrearNotaInd.as_view()), name='crear_nota_ind'),
    url(r'^notas_ind', login_required(VerNotasInd.as_view()), name='notas_ind'),
    url(r'^borrar_nota_ind/(?P<pk>\d+)/$', login_required(NotaIndDelete.as_view()), name='borrar_nota_ind'),
    url(r'^editar_nota_ind/(?P<pk>\d+)/$', login_required(NotaIndEdit.as_view()), name='editar_nota_ind'),
    #Notas Grupales
    url(r'^crear_nota_grup/(?P<id_grupo>\d+)/$', login_required(CrearNotaGrup), name='crear_nota_grup'),
    url(r'^notas_grup', login_required(VerNotasGrup.as_view()), name='notas_grup'),
    url(r'^borrar_nota_grup/(?P<pk>\d+)/$', login_required(NotaGrupDelete.as_view()), name='borrar_nota_grup'),
    url(r'^editar_nota_grup/(?P<pk>\d+)/$', login_required(NotaGrupEdit.as_view()), name='editar_nota_grup'),


]

rememberNOW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuario/', include('apps.usuarios.urls', namespace='usuarios')),
    url(r'^$', login, {'template_name':'index.html'}, name='login'),
    url(r'^accounts/login/$', login, {'template_name':'index.html'}, name='login2'),
    url(r'^notas/', include('apps.notas.urls', namespace='notas')),
    url(r'^amigos/', include('apps.amigos.urls', namespace='amigos')),
    url(r'^grupos/', include('apps.grupos.urls', namespace='grupos')),
    url(r'^logout/', logout_then_login, name='logout'),


]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
  <meta name="viewport" content="width=device-width; initial-scale=1.0">
	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">
	<script type="text/javascript" src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>

	{% block title %} <title>rememberNOW</title> {% endblock %}
</head>
<body>

<div class="container">
	{% block navbar %}
        <nav>
            <div class="logo-section">
                <a href="{% url 'login'%}"class="logo">rememberNOW</a>
                <button class="hb-button"><i class="fa fa-bars"></i></button>
            </div>
            <ul>
                <li id="menu-movil"><a href="{% url 'logout' %}">Logout</a></li>
                <li id="menu-movil"><a href="{% url 'amigos:lista_amigos' %}">Friends</a></li>
                <li id="menu-movil"><a href="{% url 'grupos:ver_grupos' %}">Groups</a></li>
                <li id="menu-movil"><a href="{% url 'notas:notas_grup' %}">Group Notes</a></li>
                <li id="menu-movil"><a href="{% url 'notas:notas_ind' %}">My Notes</a></li>
                
            </ul>
        </nav>




	{% endblock %}

<div class="rest-body-container">
	{% block contenido %}
	<h5>Este es el blocque del contenido del archivo base</h3>
	{% endblock %}
</div>
</div>


	
</body>
</html>