apps/grupos/urls.py
from django.conf.urls import url, include
from apps.grupos.views import CrearGrupo, VerGrupos
from django.contrib.auth.decorators import login_required

urlpatterns = [
    url(r'^crear_grupos$', login_required(CrearGrupo.as_view()) , name='crear_grupos'),
    url(r'^ver_grupos$', login_required(VerGrupos.as_view()) , name='ver_grupos'),
]

apps/notas/urls.py
from django.conf.urls import url, include
from apps.notas.views import CrearNotaInd, VerNotasInd, NotaIndDelete, NotaIndEdit, CrearNotaGrup, VerNotasGrup, NotaGrupDelete, NotaGrupEdit
from django.contrib.auth.decorators import login_required

urlpatterns = [
	#Notas Individuales
    url(r'^crear_nota_ind', login_required(CrearNotaInd.as_view()), name='crear_nota_ind'),
    url(r'^notas_ind', login_required(VerNotasInd.as_view()), name='notas_ind'),
    url(r'^borrar_nota_ind/(?P<pk>\d+)/$', login_required(NotaIndDelete.as_view()), name='borrar_nota_ind'),
    url(r'^editar_nota_ind/(?P<pk>\d+)/$', login_required(NotaIndEdit.as_view()), name='editar_nota_ind'),
    #Notas Grupales
    url(r'^crear_nota_grup/(?P<id_grupo>\d+)/$', login_required(CrearNotaGrup), name='crear_nota_grup'),
    url(r'^notas_grup', login_required(VerNotasGrup.as_view()), name='notas_grup'),
    url(r'^borrar_nota_grup/(?P<pk>\d+)/$', login_required(NotaGrupDelete.as_view()), name='borrar_nota_grup'),
    url(r'^editar_nota_grup/(?P<pk>\d+)/$', login_required(NotaGrupEdit.as_view()), name='editar_nota_grup'),


]

rememberNOW/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^usuario/', include('apps.usuarios.urls', namespace='usuarios')),
    url(r'^$', login, {'template_name':'index.html'}, name='login'),
    url(r'^accounts/login/$', login, {'template_name':'index.html'}, name='login2'),
    url(r'^notas/', include('apps.notas.urls', namespace='notas')),
    url(r'^amigos/', include('apps.amigos.urls', namespace='amigos')),
    url(r'^grupos/', include('apps.grupos.urls', namespace='grupos')),
    url(r'^logout/', logout_then_login, name='logout'),


]

templates/notas_grupales/crear_notas_grup.html
{% extends 'base/base.html' %}

{% block contenido %}
<h4>Create Group Note</h4>
<form method='post'>
{% csrf_token %}
{{form.as_p}}
<button type="submit">Save Group Note</button>
</form>
{% endblock %}

templates/notas_grupales/notas_grup.html
{% extends 'base/base.html' %}
{% block contenido %}

<div class="div-form3">
	<div class="titulo-nota-container">
			<h3 class="titulo-pagina">Group Notes</h3>

		<div id="div-crear-nota">
		<a id="boton-crear-nota"class="btn btn-default" href="{% url 'grupos:ver_grupos' %}">New Note</a>
		</div>
	</div>

	{% for Nota in Notas %}

	<div class="form-container">
		<h4 class="titulo-nota">Note: {{Nota.titulo}}</h4>
		<h6 class="otro-nota">Group: {{Nota.grupo.Nombre}}</h6>
		<h6 class="otro-nota">Note Creator: {{Nota.creador_nota.username}}</h6>

		<p class="cont-nota">{{Nota.contenido}}</p>

		<div class="botones-container">
		<a class="btn btn-danger" href="{% url 'notas:borrar_nota_grup' Nota.id %}">-Delete-</a>
		<a class="btn btn-warning" href="{% url 'notas:editar_nota_grup' Nota.id %}">-Edit-</a>
		</div>


	</div>

	{% endfor %}
	<a href="{% url 'grupos:ver_grupos' %}"class="form-container-new-grup">
		<h4 class="titulo-nota-new-grup">New Note</h4>

		<p class="cont-nota-new-grup">+</p>


	</a>


</div>

{% endblock %}